# Generated by Django 6.0.4 on 2026-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Wallet', 'Wallet'), ('Vehicle', 'Vehicle'), ('Person', 'Person'), ('Others', 'Others')], max_length=50),
        ),
    ]
