# Generated by Django 6.0.4 on 2026-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_claimrequest_proof_image_item_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reporting_station',
            field=models.CharField(default='Central Station', max_length=255),
        ),
    ]
